name: spring-petclinic-build-image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: spring-petclinic:latest

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix: {dir: [./sampleapps/spring-petclinic]}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ${{ matrix.dir }}
      run: 
        docker build . --file Dockerfile --tag $IMAGE_NAME
    
    - name: Push Docker image to ACR
      run: 
        docker push crspringpetclinic.azurecr.io/$IMAGE_NAME

