name: spring-petclinic-build-image

on: push
#  push:
#    tags:
#      - 'v*'
#  workflow_dispatch:
defaults:
  run:
    working-directory: ./sampleapps/spring-petclinic

jobs:
  build:
    name: Build spring-petclinic
    runs-on: ubuntu-latest
    strategy:
      matrix: {dir: [./sampleapps/spring-petclinic]}

    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: maven
        - name: Update POM with ACR NAME
          run: |
            sed -i -e "s|%%ACR_NAME%%|${{ secrets.ACR_NAME }}|g" pom.xml        
        - name: dispaly updated pom file
          run: |
            cat pom.xml
        - name: Build with Maven
#          working-directory: ${{ matrix.dir }}
          run: mvn -Djib.to.auth.username=${{ secrets.ACR_USERNAME }} -Djib.to.auth.password=${{ secrets.ACR_PASSWORD }} -Djib.to.tags=$GITHUB_RUN_NUMBER compile jib:build --file pom.xml
        - name: Update aks yaml file
          run: |
            sed -i -e "s|%%TAG%%|$GITHUB_RUN_NUMBER|g" --debug petclinic-aks.yaml        
        - name: dispaly updated aks yaml file
          run: |
            cat petclinic-aks.yaml        
