name: spring-petclinic-build-image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  IMAGE_NAME: spring-petclinic

jobs:

  build:

      runs-on: ubuntu-latest
      strategy:
        matrix: {dir: [./sampleapps/spring-petclinic]}

      steps:
      - name: Checkout code repo 
      - uses: actions/checkout@v3

      - name: Build the Docker image
        working-directory: ${{ matrix.dir }}
        run: 
          docker build . --file Dockerfile --tag spring-petclinic:latest
      
      - name: Push Docker image to ACR
        run: 
          docker image push crspringpetclinic.azurecr.io/spring-petclinic:latest