name: spring-petclinic-build-image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  build:
    name: Build spring-petclinic
    runs-on: ubuntu-latest
    strategy:
      matrix: {dir: [./sampleapps/spring-petclinic]}
    steps:
    - name: Build the Docker image 
    - uses: actions/checkout@v3
      working-directory: ${{ matrix.dir }}
      run: 
        docker build --file Dockerfile --tag spring-petclinic:latest
        docker image push crspringpetclinic.azurecr.io/spring-petclinic:latest
