name: spring-petclinic-build-image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix: {dir: [./sampleapps/spring-petclinic]}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ${{ matrix.dir }}
      run: 
        docker build . --file Dockerfile --tag spring-petclinic:latest
    
    - name: Push Docker image to ACR
      run: 
        docker push crspringpetclinic.azurecr.io/spring-petclinic:latest

