name: spring-petclinic-build-image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  build:
    name: Build spring-petclinic
    runs-on: ubuntu-latest
    strategy:
      matrix: {dir: [./sampleapps/spring-petclinic]}

    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: maven
        - name: Build with Maven
          working-directory: ${{ matrix.dir }}
          run: mvn -Djib.from.auth.username=crspringpetclinic -Djib.from.auth.password=b5ZPmuURBviEHrjPveuu=5EG4NRvsvnG compile jib:build --file pom.xml