name: spring-petclinic-build-image

on: push
#  push:
#    tags:
#      - 'v*'
#  workflow_dispatch:
defaults:
  run:
    working-directory: ./sampleapps/spring-petclinic

jobs:
  build:
    name: Build spring-petclinic
    runs-on: ubuntu-latest
    strategy:
      matrix: {dir: [./sampleapps/spring-petclinic]}

    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: maven
        - name: Build with Maven
#          working-directory: ${{ matrix.dir }}
          run: mvn -Djib.to.auth.username=${{ secrets.ACR_USERNAME }} -Djib.to.auth.password=${{ secrets.ACR_PASSWORD }} -Djib.to.tags=$GITHUB_RUN_NUMBER compile jib:build --file pom.xml
        - run: ls
        - name: Update aks yaml file
          run: |
            sed -i -e "s|%%TAG%%|$GITHUB_RUN_NUMBER|g" petclinic-aks.yaml        
        - name: Read petclinic-aks.yaml
          id: package
          uses: juliangruber/read-file-action@v1
          with:
            path: petclinic-aks.yaml
        - name: Echo petclinic-aks.yaml
          run: echo "${{ steps.package.outputs.content }}"        
        - uses: bluwy/substitute-string-action@v1
          id: sub
          with:
            _input-file: './petclinic-aks.yaml'
            _format-key: '%%key%%'
            imagetag: $GITHUB_RUN_NUMBER
